### PR TITLE
Allow same input/output

### PR DESCRIPTION
**Pull request by rrey**
Make replacement in two steps to allow usage of same input/output with the action.

### CODE REVIEW

**Comment by danielr1996** [comment]
Thanks for your contribution, can you post an example of what would be possible with your solution, I think I'm not fully understanding the benefits yet.

**Comment by rrey** [comment]
Sure, at the moment the following would result in an empty output:
```
- uses: danielr1996/envsubst-action@1.0.0
  env:
      SOME_VAR: 1.2.3
      SOME_OTHER_VAR: staging
  with:
    input: deployment.json
    output: deployment.json
```
With my patch, introducing a temporary file allows this usage.

**Comment by danielr1996** [comment]
Well that makes sense.

**Comment by rrey** [comment]
@danielr1996 : Could you release this patch with a new action version ? thanks

**Comment by danielr1996** [comment]
https://github.com/danielr1996/envsubst-action/releases/tag/1.1.0 here you go

**Pull request merged**
